Adição das novas funcionalidades Clone e Copy
ghiorzi/pandemonium pull request #10
Opened 2020-12-05 19:52 UTC by VitorSouza23

Adição das novas funcionalidades Clone e Copy

Object.Clone(): Usa a estratégia de serialização em memória para criar uma cópia dos dados e gerar uma nova referência totalmente independente do objeto original. O objeto que usar este método obrigatoriamente precisa ser uma instância de uma classe que possui o atributo "Serializable".

IEnumerable.Copy(): Seguindo a mesma ideia do Clone, mas voltado para classes que implementam a interface genérica IEnumerable<>, este método usa internamente o Object.Clone() para gerar uma nova referência de memória totalmente independente da anterior. A coleção genérica do tipo "T" obrigatoriamente precisa ser uma instância de uma classe que possui o atributo "Serializable".

2020-12-06 13:32 UTC, ghiorzi commented on Pandemonium/Extensions/Object/Object.Clone.cs
> +        /// Returns a clone of the object, with a new memory reference. <b>The class needs be Serializable</b>.
### Sugestão
Acredito que ficaria melhor trocar "needs be Serializable" por "must be serializable"

### Motivo
**_Must_** é comumente usado no contexto de obrigação, sendo ele mais enfático que o verbo **_need_** neste caso

2020-12-06 13:36 UTC, ghiorzi commented on Pandemonium/Extensions/Object/Object.Clone.cs
> +            MemoryStream stream = new MemoryStream();
### Sugestão

Devido ao **_MemoryStream_** ser um recurso **_disposable_**, seria interessante usá-lo em um **_using block_**

### Exemplificação

```cs
 using (var stream = new MemoryStream())
 {
 }
```

2020-12-06 13:40 UTC, ghiorzi commented on Pandemonium/Extensions/IEnumerable/IEnumerable.Copy.cs
> +        /// Return a non memory reference copy of enumeration. <b>The class of enumeration needs be Serializable</b>;
### Sugestões

1. Alterar _Return_ para _Returns_;
2. Alterar "he class of enumeration needs be Serializable" para "The type must be serializable".

Observação: o motivo do _**must**_ está descrito no _review_ do método _**Clone**_

2020-12-06 13:44 UTC, ghiorzi requested changes
Obrigado pela contribuição com o projeto :)

Deixei algumas sugestões no _review_, beleza?

2020-12-07 11:07 UTC, VitorSouza23 commented
Boa tio Rodrigo! Nos próximos dias aplico as correções!

2020-12-07 11:19 UTC, VitorSouza23 commented on Pandemonium/Extensions/Object/Object.Clone.cs
> +        /// Returns a clone of the object, with a new memory reference. <b>The class needs be Serializable</b>.
Feito!!!

2020-12-07 11:19 UTC, VitorSouza23 commented on Pandemonium/Extensions/Object/Object.Clone.cs
> +            MemoryStream stream = new MemoryStream();
Feito!!!

2020-12-07 11:19 UTC, VitorSouza23 commented on Pandemonium/Extensions/IEnumerable/IEnumerable.Copy.cs
> +        /// Return a non memory reference copy of enumeration. <b>The class of enumeration needs be Serializable</b>;
Feito!!!

2020-12-07 11:20 UTC, VitorSouza23 commented
Alterações feitas tio Rodrigo! Qualquer outra mudança só chamar 😁

2020-12-07 22:32 UTC, ghiorzi approved these changes

2020-12-07 22:33 UTC, merged